template: templates/loz-script-project.yaml
overrides:
  artifacts:
    - type: script
      version: 1.12.4
      build_script:
        repo_name: linux-on-ibm-z-scripts
        path: src/build.sh
        #args: --version 1.12.4
        docker_image: ubuntu:22.04
