template: templates/script-project.yaml
overrides:
  artifacts:
    - type: script
      build_script:
        repo_name: linux-on-ibm-z-scripts
        path: src/build.sh
        args: --version 1.21 --testarg 3.25
        docker_image: ubuntu:22.04
